// Code generated by MockGen. DO NOT EDIT.
// Source: book_query_service.go
//
// Generated by this command:
//
//	mockgen -source=book_query_service.go -destination=mocks/mock_book_query_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	query "github.com/YK4651/library-clean-architecture/internal/application/query"
	gomock "go.uber.org/mock/gomock"
)

// MockBookQueryService is a mock of BookQueryService interface.
type MockBookQueryService struct {
	ctrl     *gomock.Controller
	recorder *MockBookQueryServiceMockRecorder
	isgomock struct{}
}

// MockBookQueryServiceMockRecorder is the mock recorder for MockBookQueryService.
type MockBookQueryServiceMockRecorder struct {
	mock *MockBookQueryService
}

// NewMockBookQueryService creates a new mock instance.
func NewMockBookQueryService(ctrl *gomock.Controller) *MockBookQueryService {
	mock := &MockBookQueryService{ctrl: ctrl}
	mock.recorder = &MockBookQueryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookQueryService) EXPECT() *MockBookQueryServiceMockRecorder {
	return m.recorder
}

// GetBookByID mocks base method.
func (m *MockBookQueryService) GetBookByID(ctx context.Context, bookID string) (*query.BookReadModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookByID", ctx, bookID)
	ret0, _ := ret[0].(*query.BookReadModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookByID indicates an expected call of GetBookByID.
func (mr *MockBookQueryServiceMockRecorder) GetBookByID(ctx, bookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookByID", reflect.TypeOf((*MockBookQueryService)(nil).GetBookByID), ctx, bookID)
}

// ListBooks mocks base method.
func (m *MockBookQueryService) ListBooks(ctx context.Context) ([]*query.BookReadModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBooks", ctx)
	ret0, _ := ret[0].([]*query.BookReadModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBooks indicates an expected call of ListBooks.
func (mr *MockBookQueryServiceMockRecorder) ListBooks(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBooks", reflect.TypeOf((*MockBookQueryService)(nil).ListBooks), ctx)
}
