// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/YK4651/library-clean-architecture/internal/application/borrowbook (interfaces: IUserRepository,IBookRepository,ILoanRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_repositories.go -package=mocks . IUserRepository,IBookRepository,ILoanRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	bookdm "github.com/YK4651/library-clean-architecture/internal/domain/bookdm"
	loandm "github.com/YK4651/library-clean-architecture/internal/domain/loandm"
	userdm "github.com/YK4651/library-clean-architecture/internal/domain/userdm"
	gomock "go.uber.org/mock/gomock"
)

// MockIUserRepository is a mock of IUserRepository interface.
type MockIUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIUserRepositoryMockRecorder
	isgomock struct{}
}

// MockIUserRepositoryMockRecorder is the mock recorder for MockIUserRepository.
type MockIUserRepositoryMockRecorder struct {
	mock *MockIUserRepository
}

// NewMockIUserRepository creates a new mock instance.
func NewMockIUserRepository(ctrl *gomock.Controller) *MockIUserRepository {
	mock := &MockIUserRepository{ctrl: ctrl}
	mock.recorder = &MockIUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUserRepository) EXPECT() *MockIUserRepositoryMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockIUserRepository) FindByID(ctx context.Context, id *userdm.UserID) (*userdm.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*userdm.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockIUserRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockIUserRepository)(nil).FindByID), ctx, id)
}

// MockIBookRepository is a mock of IBookRepository interface.
type MockIBookRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIBookRepositoryMockRecorder
	isgomock struct{}
}

// MockIBookRepositoryMockRecorder is the mock recorder for MockIBookRepository.
type MockIBookRepositoryMockRecorder struct {
	mock *MockIBookRepository
}

// NewMockIBookRepository creates a new mock instance.
func NewMockIBookRepository(ctrl *gomock.Controller) *MockIBookRepository {
	mock := &MockIBookRepository{ctrl: ctrl}
	mock.recorder = &MockIBookRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIBookRepository) EXPECT() *MockIBookRepositoryMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockIBookRepository) FindByID(ctx context.Context, id *bookdm.BookID) (*bookdm.Book, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*bookdm.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockIBookRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockIBookRepository)(nil).FindByID), ctx, id)
}

// MockILoanRepository is a mock of ILoanRepository interface.
type MockILoanRepository struct {
	ctrl     *gomock.Controller
	recorder *MockILoanRepositoryMockRecorder
	isgomock struct{}
}

// MockILoanRepositoryMockRecorder is the mock recorder for MockILoanRepository.
type MockILoanRepositoryMockRecorder struct {
	mock *MockILoanRepository
}

// NewMockILoanRepository creates a new mock instance.
func NewMockILoanRepository(ctrl *gomock.Controller) *MockILoanRepository {
	mock := &MockILoanRepository{ctrl: ctrl}
	mock.recorder = &MockILoanRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILoanRepository) EXPECT() *MockILoanRepositoryMockRecorder {
	return m.recorder
}

// CountActiveLoansForBook mocks base method.
func (m *MockILoanRepository) CountActiveLoansForBook(ctx context.Context, bookID *bookdm.BookID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveLoansForBook", ctx, bookID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActiveLoansForBook indicates an expected call of CountActiveLoansForBook.
func (mr *MockILoanRepositoryMockRecorder) CountActiveLoansForBook(ctx, bookID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveLoansForBook", reflect.TypeOf((*MockILoanRepository)(nil).CountActiveLoansForBook), ctx, bookID)
}

// CountActiveLoansForUser mocks base method.
func (m *MockILoanRepository) CountActiveLoansForUser(ctx context.Context, userID *userdm.UserID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveLoansForUser", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActiveLoansForUser indicates an expected call of CountActiveLoansForUser.
func (mr *MockILoanRepositoryMockRecorder) CountActiveLoansForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveLoansForUser", reflect.TypeOf((*MockILoanRepository)(nil).CountActiveLoansForUser), ctx, userID)
}

// Save mocks base method.
func (m *MockILoanRepository) Save(ctx context.Context, loan *loandm.Loan) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, loan)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockILoanRepositoryMockRecorder) Save(ctx, loan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockILoanRepository)(nil).Save), ctx, loan)
}
